import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import "../globals.css";

import "@fontsource/poppins";
import { Chatbot } from "./ui/chat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex">
          <Sidebar />
          <main className="flex-1 p-4 bg-cover bg-center min-h-screen font-[poppins]" >
            {children}
          </main>
        </div>

        <div className="font-[poppins]">
          <Chatbot />
        </div>
      </body>
    </html>
  );
}

