import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AdminSidebar from "@/components/sidebar/AdminSidebar";
import "@/app/globals.css";

import "@fontsource/poppins";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex font-[poppins]">
          <AdminSidebar />
          <main className="flex-1 p-4 bg-cover bg-center md:mt-0 mt-10 max-w-3xl md:mx-auto mx-2" >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}

